				//// PRACTICE ONLY FOR ME ////



		// let a=5;
		// if(a>=5){
		//   console.log("this value is greater than 5 ok");
		// }
		// let b=5,c=10;
		// for(let i=0;i<=c;i++){
		//   console.log("hello vijay");
		// }

		      /// this is a switch program  ///
		// let age=prompt("what is your age")
		let age=18;
		switch(age)
		{
		  case 20:
		  console.log("welcome to the drive car");
		  break

		  case 18:
		  console.log("can can drive comfidently");
		  break

		  default:
		  console.log("please enter valid age okay")
		}

		let num = 6;
		num = parseInt(num);

		if (num % 2 == 0 && num % 3 == 0) {
		  console.log("num is divisible by 2 and 3");
		} else {
		  console.log("not divisible");
		}